apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: codeserver-tls
  namespace: codeserver
spec:
  secretName: codeserver-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - code.nicknoonan.net