apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver
  namespace: codeserver
spec:
  replicas: 0
  strategy:
    type: Recreate # Ensures volume detaches cleanly on updates
  selector:
    matchLabels:
      app: codeserver
  template:
    metadata:
      labels:
        app: codeserver
    spec:
      nodeSelector:
        kubernetes.io/hostname: bigboi
      tolerations:
      - key: bigboi
        operator: Exists
        effect: NoSchedule
      containers:
      - name: codeserver
        image: ghcr.io/nicknoonan/k8cluster/codeserver:sha-7846807
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SUDO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: codeserver-secret
              key: password
        volumeMounts:
        - name: codeserver-data
          mountPath: /config
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
      volumes:
      - name: codeserver-data
        persistentVolumeClaim:
          claimName: codeserver
