apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver
  namespace: codeserver
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi