apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nicknoonan/k8cluster.git'  # <--- Your Git Repo
    targetRevision: HEAD
    path: cert-manager/cluster-issuer                 # <--- Folder with issuer YAML
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true   # <--- Prevents failure before CRDs are registered