apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-power-manager.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "node-power-manager.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
