apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
  namespace: minecraft
data:
  server.properties: |
    motd=shrimpcraft
    difficulty=normal
    gamemode=survival
    max-players=10
    enable-command-block=true
    online-mode=false
    view-distance=10
    simulation-distance=10
