apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  nicknoonan.server: |
    nicknoonan.net:53 {
        errors
        cache 30

        # Rewrite rules placed at the server block root
        rewrite name exact ai.nicknoonan.net internal-cluster.nicknoonan.net
        rewrite name exact argocd.nicknoonan.net internal-cluster.nicknoonan.net
        rewrite name exact code.nicknoonan.net internal-cluster.nicknoonan.net
        rewrite name exact cs2.nicknoonan.net internal-cluster.nicknoonan.net
        rewrite name exact grafana.nicknoonan.net internal-cluster.nicknoonan.net
        rewrite name exact headlamp.nicknoonan.net internal-cluster.nicknoonan.net
        rewrite name exact idp.nicknoonan.net internal-cluster.nicknoonan.net
        rewrite name exact k8s-mcp.nicknoonan.net internal-cluster.nicknoonan.net

        hosts {
            192.168.1.111 internal-cluster.nicknoonan.net
            fallthrough
        }
        forward . 1.1.1.1 8.8.8.8
    }