{{- if .Values.nodeDnsConfigurator.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-dns-configurator
  namespace: {{ .Release.Namespace }}
  labels:
    app: node-dns-configurator
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: node-dns-configurator
  template:
    metadata:
      labels:
        app: node-dns-configurator
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
        - operator: Exists
      initContainers:
        - name: setup-systemd-resolved
          image: {{ .Values.nodeDnsConfigurator.image.alpine }}
          securityContext:
            privileged: true
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "Checking systemd-resolved configuration..."

              RESOLVED_CONF="/host/etc/systemd/resolved.conf"

              if ! grep -q "^DNS={{ .Values.nodeDnsConfigurator.clusterDnsIp }}" "$RESOLVED_CONF"; then
                echo "Adding DNS={{ .Values.nodeDnsConfigurator.clusterDnsIp }} to $RESOLVED_CONF"
                sed -i '/^\[Resolve\]/a DNS={{ .Values.nodeDnsConfigurator.clusterDnsIp }}' "$RESOLVED_CONF"
              fi

              if ! grep -q "^Domains=~\." "$RESOLVED_CONF"; then
                echo "Adding Domains=~. to $RESOLVED_CONF"
                sed -i '/^\[Resolve\]/a Domains=~.' "$RESOLVED_CONF"
              fi

              echo "Applying changes and restarting systemd-resolved on host..."
              nsenter --target 1 --mount --uts --ipc --net --pid -- systemctl restart systemd-resolved

              echo "DNS configuration successfully updated."
          volumeMounts:
            - name: host-etc
              mountPath: /host/etc
      containers:
        - name: pause
          image: {{ .Values.nodeDnsConfigurator.image.pause }}
          resources:
            limits:
              cpu: 10m
              memory: 16Mi
            requests:
              cpu: 10m
              memory: 16Mi
      volumes:
        - name: host-etc
          hostPath:
            path: /etc
            type: Directory
{{- end }}