image:
  repository: ghcr.io/nicknoonan/k8cluster/platform
  tag: ""
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

service:
  type: ClusterIP
  port: 8080

config:
  targetNodeName: ""
  targetMacAddress: ""
  targetIp: ""
  sshUser: root
  sshShutdownCommand: "sudo shutdown now"
  sshSecretName: node-power-manager-ssh
  managedDeployments: []

ingress:
  enabled: false
  host: ""
  tlsSecretName: ""

resources:
  requests:
    cpu: "100m"
    memory: 50Mi
  limits:
    cpu: "100m"
    memory: 50Mi
