apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-power-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nicknoonan/k8cluster.git'
    targetRevision: HEAD
    path: platform/charts/node-power-manager
    helm:
      releaseName: node-power-manager
      values: |
        image:
          repository: ghcr.io/nicknoonan/k8cluster/node-power-manager
          tag: sha-a5a6228
        config:
          targetNodeName: "bigboi"
          targetMacAddress: "00:d8:61:59:88:14"
          targetIp: "192.168.1.112"
          # Set this to the account that has the node-power-manager public key in authorized_keys.
          sshUser: "nick"
          sshShutdownCommand: "sudo shutdown now"
          sshSecretName: node-power-manager-ssh
          managedDeployments: []
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
