image:
  repository: ghcr.io/nicknoonan/k8cluster/platform
  tag: ""
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

service:
  type: ClusterIP
  port: 8080

config:
  targetNodeName: ""
  targetMacAddress: ""
  targetIp: ""
  sshUser: root
  sshSecretName: node-power-manager-ssh
  managedDeployments: []

resources: {}
