apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 65.x.x
    helm:
      values: |
        prometheus:
          prometheusSpec:
            retention: 7d
            resources:
              requests:
                memory: 512Mi
                cpu: 250m
              limits:
                memory: 512Gi
                cpu: 500m
        grafana:
          adminPassword: "admin"
          persistence:
            enabled: true
            size: 2Gi
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki.monitoring.svc.cluster.local:3100
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - grafana.nicknoonan.net
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.nicknoonan.net
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true