apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: loki
    targetRevision: 6.x.x
    helm:
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage:
            type: filesystem
            filesystem:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules
          compactor:
            working_directory: /var/loki/compactor
        singleBinary:
          replicas: 1
          resources:
            requests:
              cpu: "100m"
              memory: 800Mi
            limits:
              cpu: "100m"
              memory: 800Mi
          persistence:
            enabled: true
            size: 10Gi
        gateway:
          enabled: false
        lokiCanary:
          enabled: false
        test:
          enabled: false
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true