apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: loki
    targetRevision: 6.x.x
    helm:
      values: |
        deploymentMode: SingleBinary
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 10Gi
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        loki:
          storage:
            type: filesystem
            bucketNames:
              chunks: "dummy-chunks"
              ruler: "dummy-ruler"
              admin: "dummy-admin"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true