apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cs2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nicknoonan/k8cluster.git'
    targetRevision: HEAD
    path: cs2/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cs2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
