apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      releaseName: nfs
      values: |
        resources:
          requests:
            cpu: "100m"
            memory: 200Mi
          limits:
            cpu: "200m"
            memory: 200Mi
        nfs:
          server: 192.168.1.111
          path: /mnt/k3s-nfs
        storageClass:
          create: true
          defaultClass: true
          allowVolumeExpansion: false
          archiveOnDelete: true
          name: nfs
          provisionerName: k8s-sigs.io/nfs
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true