internalDatabase:
  enabled: false

nextcloud:
  host: cloud.nicknoonan.net
  trustedDomains:
    - cloud.nicknoonan.net
  username: admin
  password: admin

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  path: /
  pathType: Prefix
  tls:
    - secretName: nextcloud-tls
      hosts:
        - cloud.nicknoonan.net

persistence:
  enabled: true
  storageClass: local-path
  accessMode: ReadWriteOnce
  size: 100Gi
  nextcloudData:
    enabled: true
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 250Gi

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: nextcloud
        password: "password"
        database: nextcloud
  primary:
    persistence:
      enabled: true
      storageClass: local-path
      size: 20Gi

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 2Gi

cronjob:
  enabled: true
  type: cronjob
